DROP TABLE IF EXISTS ingestion_state CASCADE;
DROP TABLE IF EXISTS network_stats CASCADE;
DROP TABLE IF EXISTS offers CASCADE;
DROP TABLE IF EXISTS liquidity_pools CASCADE;
DROP TABLE IF EXISTS known_accounts CASCADE;
